import Head from 'next/head'
import type { NextPage } from 'next'

import { Leftbar, Navbar, Rightbar, Update } from '../components'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>My Redux Toolkit</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/redux.svg' />
      </Head>

      <Navbar />
      <div className='container'>
        <Leftbar />
        <Update />
        <Rightbar />
      </div>
    </>
  )
}

export default Home
